Repository cognitedata/python-extractor-utils, pull requests merged in 2025-07, with the labels that each got.

#454 Rename local_override to force_local_config
  cognite/extractorutils/unstable/core/runtime.py
  tests/test_unstable/test_runtime.py
Labels: risk-review-ongoing

#452 [unstable] Add log level override
  CHANGELOG.md
  cognite/extractorutils/unstable/core/base.py
  cognite/extractorutils/unstable/core/runtime.py
  tests/test_unstable/conftest.py
  tests/test_unstable/test_base.py
Labels: risk-review-ongoing, waiting-for-risk-review, waiting-for-team

#460 Add example extractor to run unstable
  cognite/examples/unstable/extractors/simple_extractor/config/config.yaml
  cognite/examples/unstable/extractors/simple_extractor/config/connection_config.yaml
  cognite/examples/unstable/extractors/simple_extractor/main.py
  pyproject.toml
Labels: risk-review-ongoing, waiting-for-team

#461 Move and update dtos
  cognite/extractorutils/unstable/configuration/models.py
  cognite/extractorutils/unstable/core/_dto.py
  cognite/extractorutils/unstable/core/base.py
  cognite/extractorutils/unstable/core/runtime.py
  tests/test_unstable/test_base.py
  tests/test_unstable/test_errors.py
Labels: risk-review-ongoing, waiting-for-team
